// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrhttonrlgqynhenlxfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyaHR0b25ybGdxeW5oZW5seGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDI1MTIsImV4cCI6MjA2NTgxODUxMn0.mf80UMTFjwUWxIYkX5D02jhavM8xkhNTyHyxN9FYskI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);